// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace KataGameOfLife.Spec.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Game Of Life", Description="\tAs a \"Game of Life\" observer\r\n\tIn order to play The game with a zero-player\r\n\tI " +
        "want analyse state and observing how it evolved", SourceFile="Features\\GameOfLife.feature", SourceLine=0)]
    public partial class GameOfLifeFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GameOfLife.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Game Of Life", "\tAs a \"Game of Life\" observer\r\n\tIn order to play The game with a zero-player\r\n\tI " +
                    "want analyse state and observing how it evolved", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Alive cell with zero neighbours alive:\t0\t0", Description="\t\t\t\t\t\t\t\t\t\t\t\t\t0\t1", SourceLine=6)]
        public virtual void AliveCellWithZeroNeighboursAlive00()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alive cell with zero neighbours alive:\t0\t0", "\t\t\t\t\t\t\t\t\t\t\t\t\t0\t1", ((string[])(null)));
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
 testRunner.Given("initial \"Alive\" state cell with (0) alive neighbours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.When("I determine next generation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then("next generation is \"Dead\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Alive cell with one neighbour alive:\t0\t1", Description="\t\t\t\t\t\t\t\t\t\t\t\t0\t1", SourceLine=13)]
        public virtual void AliveCellWithOneNeighbourAlive01()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alive cell with one neighbour alive:\t0\t1", "\t\t\t\t\t\t\t\t\t\t\t\t0\t1", ((string[])(null)));
#line 14
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 16
 testRunner.Given("initial \"Alive\" state cell with (1) alive neighbours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
 testRunner.When("I determine next generation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
 testRunner.Then("next generation is \"Dead\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Alive cell with two neighbours alive:\t1\t1", Description="\t\t\t\t\t\t\t\t\t\t\t\t0\t1", SourceLine=19)]
        public virtual void AliveCellWithTwoNeighboursAlive11()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alive cell with two neighbours alive:\t1\t1", "\t\t\t\t\t\t\t\t\t\t\t\t0\t1", ((string[])(null)));
#line 20
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 22
 testRunner.Given("initial \"Alive\" state cell with (2) alive neighbours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 23
 testRunner.When("I determine next generation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
 testRunner.Then("next generation is \"Alive\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("A live cell with three neighbours alive:\t1\t1", Description="\t\t\t\t\t\t\t\t\t\t\t\t\t1\t1", SourceLine=25)]
        public virtual void ALiveCellWithThreeNeighboursAlive11()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A live cell with three neighbours alive:\t1\t1", "\t\t\t\t\t\t\t\t\t\t\t\t\t1\t1", ((string[])(null)));
#line 26
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 28
 testRunner.Given("initial \"Alive\" state cell with (3) alive neighbours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 29
 testRunner.When("I determine next generation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.Then("next generation is \"Alive\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Dead cell with zero neighbours alive:\t0\t0", Description="\t\t\t\t\t\t\t\t\t\t\t\t0\t0", SourceLine=31)]
        public virtual void DeadCellWithZeroNeighboursAlive00()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dead cell with zero neighbours alive:\t0\t0", "\t\t\t\t\t\t\t\t\t\t\t\t0\t0", ((string[])(null)));
#line 32
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 34
 testRunner.Given("initial \"Dead\" state cell with (0) alive neighbours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 35
 testRunner.When("I determine next generation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 36
 testRunner.Then("next generation is \"Dead\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Dead cell with one neighbour alive:\t0\t1", Description="\t\t\t\t\t\t\t\t\t\t\t\t0\t0", SourceLine=37)]
        public virtual void DeadCellWithOneNeighbourAlive01()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dead cell with one neighbour alive:\t0\t1", "\t\t\t\t\t\t\t\t\t\t\t\t0\t0", ((string[])(null)));
#line 38
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 40
 testRunner.Given("initial \"Dead\" state cell with (1) alive neighbours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 41
 testRunner.When("I determine next generation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
 testRunner.Then("next generation is \"Dead\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Dead cell with two neighbours alive:\t1\t1", Description="\t\t\t\t\t\t\t\t\t\t\t\t0\t0", SourceLine=43)]
        public virtual void DeadCellWithTwoNeighboursAlive11()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dead cell with two neighbours alive:\t1\t1", "\t\t\t\t\t\t\t\t\t\t\t\t0\t0", ((string[])(null)));
#line 44
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 46
 testRunner.Given("initial \"Dead\" state cell with (2) alive neighbours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 47
 testRunner.When("I determine next generation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 48
 testRunner.Then("next generation is \"Dead\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Dead cell with three neighbours alive:\t1\t1", Description="\t\t\t\t\t\t\t\t\t\t\t\t\t1\t0", SourceLine=49)]
        public virtual void DeadCellWithThreeNeighboursAlive11()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dead cell with three neighbours alive:\t1\t1", "\t\t\t\t\t\t\t\t\t\t\t\t\t1\t0", ((string[])(null)));
#line 50
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 52
 testRunner.Given("initial \"Dead\" state cell with (3) alive neighbours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 53
 testRunner.When("I determine next generation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
 testRunner.Then("next generation is \"Alive\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Dead cell with more than three neighbours alive:\t1\t1\t1", Description="\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t1\t0\t1\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\t0\t0", SourceLine=55)]
        public virtual void DeadCellWithMoreThanThreeNeighboursAlive111()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dead cell with more than three neighbours alive:\t1\t1\t1", "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t1\t0\t1\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\t0\t0", ((string[])(null)));
#line 56
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 59
 testRunner.Given("initial \"Dead\" state cell with (4) alive neighbours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 60
 testRunner.When("I determine next generation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 61
 testRunner.Then("next generation is \"Dead\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Alive cell with more than three neighbours alive:\t1\t1\t1", Description="\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t1\t1\t1\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\t0\t0", SourceLine=62)]
        public virtual void AliveCellWithMoreThanThreeNeighboursAlive111()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alive cell with more than three neighbours alive:\t1\t1\t1", "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t1\t1\t1\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\t0\t0", ((string[])(null)));
#line 63
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 66
 testRunner.Given("initial \"Alive\" state cell with (4) alive neighbours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 67
 testRunner.When("I determine next generation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 68
 testRunner.Then("next generation is \"Dead\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
